const fs = require("node:fs");
const path = require("node:path");
const YAML = require("yamljs");
const parser = require("@apidevtools/swagger-parser");
const contract = require("../contracts/api");
async function main() {
  await parser.validate(structuredClone(contract));
  const output = "# Generated by npm run contracts:generate. Edit contracts/api.js or Zod validators.\n" + YAML.stringify(contract, 100, 2);
  const file = path.join(__dirname, "../openapi.yaml");
  if (process.argv.includes("--check")) {
    if (fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n") !== output.replace(/\r\n/g, "\n")) throw new Error("OpenAPI is stale. Run npm run contracts:generate");
  } else fs.writeFileSync(file, output);
  console.log(`Validated ${Object.keys(contract.paths).length} API paths`);
}
main().catch((error) => { console.error(error.message); process.exitCode = 1; });
